### ISSUE TITLE
麻烦大佬v1.0.0后面的修复提交打个tag

### ISSUE THREAD

**Issue by 467892746** [antlinker/alog#2]
v1.0.0版本有个致命bug
![image](https://user-images.githubusercontent.com/46819001/158132596-2fb954e9-7d8d-4f55-a2c3-1808845adf8c.png)
此处不判断error的话,会有空指针风险，导致panic出现。我们今天线上就出现了这个问题。后面对比发现master分支是修复了这个问题的。但是我们使用go mod 拉取的时候默认拉取的最新版本是v1.0.0版本。虽然我们现在在go mod 后面指定了master拉取，更新了版本。但是为了以防后来者也出现这个问题，麻烦作者有时间打个新版本的tag。

**Comment by yinbaoqiang** [comment]
已经发布 [v1.1.0](https://github.com/antlinker/alog/releases/tag/v1.1.0) 增加了go mod 支持
